#!/bin/bash

############################################
## Fine-tuning mode: Linear probing
############################################

### Electricity
python3 scripts/finetuning/imputation.py\
 --finetuning_mode 'linear-probing'\
 --config 'configs/imputation/linear_probing.yaml'\
 --gpu_id 1\
 --init_lr 0.001\
 --max_epoch 5\
  --train_batch_size 4\
 --val_batch_size 8\
 --dataset_names '/media3/Timeseries-PILE/forecasting/autoformer/electricity.csv'\
 --level 0
 python3 scripts/finetuning/imputation.py\
 --finetuning_mode 'linear-probing'\
 --config 'configs/imputation/linear_probing.yaml'\
 --gpu_id 1\
 --init_lr 0.001\
 --max_epoch 5\
  --train_batch_size 4\
 --val_batch_size 8\
 --dataset_names '/media3/Timeseries-PILE/forecasting/autoformer/electricity.csv'\
 --level 1
 python3 scripts/finetuning/imputation.py\
 --finetuning_mode 'linear-probing'\
 --config 'configs/imputation/linear_probing.yaml'\
 --gpu_id 1\
 --init_lr 0.001\
 --max_epoch 5\
  --train_batch_size 4\
 --val_batch_size 8\
 --dataset_names '/media3/Timeseries-PILE/forecasting/autoformer/electricity.csv'\
 --level 2
 python3 scripts/finetuning/imputation.py\
 --finetuning_mode 'linear-probing'\
 --config 'configs/imputation/linear_probing.yaml'\
 --gpu_id 1\
 --init_lr 0.001\
 --max_epoch 5\
  --train_batch_size 4\
 --val_batch_size 8\
 --dataset_names '/media3/Timeseries-PILE/forecasting/autoformer/electricity.csv'\
 --level 3
 python3 scripts/finetuning/imputation.py\
 --finetuning_mode 'linear-probing'\
 --config 'configs/imputation/linear_probing.yaml'\
 --gpu_id 1\
 --init_lr 0.001\
 --max_epoch 5\
  --train_batch_size 4\
 --val_batch_size 8\
 --dataset_names '/media3/Timeseries-PILE/forecasting/autoformer/electricity.csv'\
 --level 4
 python3 scripts/finetuning/imputation.py\
 --finetuning_mode 'linear-probing'\
 --config 'configs/imputation/linear_probing.yaml'\
 --gpu_id 1\
 --init_lr 0.001\
 --max_epoch 5\
  --train_batch_size 4\
 --val_batch_size 8\
 --dataset_names '/media3/Timeseries-PILE/forecasting/autoformer/electricity.csv'\
 --level 5
 python3 scripts/finetuning/imputation.py\
 --finetuning_mode 'linear-probing'\
 --config 'configs/imputation/linear_probing.yaml'\
 --gpu_id 1\
 --init_lr 0.001\
 --max_epoch 5\
  --train_batch_size 4\
 --val_batch_size 8\
 --dataset_names '/media3/Timeseries-PILE/forecasting/autoformer/electricity.csv'\
 --level 6
 python3 scripts/finetuning/imputation.py\
 --finetuning_mode 'linear-probing'\
 --config 'configs/imputation/linear_probing.yaml'\
 --gpu_id 1\
 --init_lr 0.001\
 --max_epoch 5\
  --train_batch_size 4\
 --val_batch_size 8\
 --dataset_names '/media3/Timeseries-PILE/forecasting/autoformer/electricity.csv'\
 --level 7
 python3 scripts/finetuning/imputation.py\
 --finetuning_mode 'linear-probing'\
 --config 'configs/imputation/linear_probing.yaml'\
 --gpu_id 1\
 --init_lr 0.001\
 --max_epoch 5\
  --train_batch_size 4\
 --val_batch_size 8\
 --dataset_names '/media3/Timeseries-PILE/forecasting/autoformer/electricity.csv'\
 --level 8
 python3 scripts/finetuning/imputation.py\
 --finetuning_mode 'linear-probing'\
 --config 'configs/imputation/linear_probing.yaml'\
 --gpu_id 1\
 --init_lr 0.001\
 --max_epoch 5\
  --train_batch_size 4\
 --val_batch_size 8\
 --dataset_names '/media3/Timeseries-PILE/forecasting/autoformer/electricity.csv'\
 --level 9
 python3 scripts/finetuning/imputation.py\
 --finetuning_mode 'linear-probing'\
 --config 'configs/imputation/linear_probing.yaml'\
 --gpu_id 1\
 --init_lr 0.001\
 --max_epoch 5\
  --train_batch_size 4\
 --val_batch_size 8\
 --dataset_names '/media3/Timeseries-PILE/forecasting/autoformer/electricity.csv'\
 --level 10
 python3 scripts/finetuning/imputation.py\
 --finetuning_mode 'linear-probing'\
 --config 'configs/imputation/linear_probing.yaml'\
 --gpu_id 1\
 --init_lr 0.001\
 --max_epoch 5\
  --train_batch_size 4\
 --val_batch_size 8\
 --dataset_names '/media3/Timeseries-PILE/forecasting/autoformer/electricity.csv'\
 --level 11
 python3 scripts/finetuning/imputation.py\
 --finetuning_mode 'linear-probing'\
 --config 'configs/imputation/linear_probing.yaml'\
 --gpu_id 1\
 --init_lr 0.001\
 --max_epoch 5\
  --train_batch_size 4\
 --val_batch_size 8\
 --dataset_names '/media3/Timeseries-PILE/forecasting/autoformer/electricity.csv'\
 --level 12
 python3 scripts/finetuning/imputation.py\
 --finetuning_mode 'linear-probing'\
 --config 'configs/imputation/linear_probing.yaml'\
 --gpu_id 1\
 --init_lr 0.001\
 --max_epoch 5\
  --train_batch_size 4\
 --val_batch_size 8\
 --dataset_names '/media3/Timeseries-PILE/forecasting/autoformer/electricity.csv'\
 --level 13
 python3 scripts/finetuning/imputation.py\
 --finetuning_mode 'linear-probing'\
 --config 'configs/imputation/linear_probing.yaml'\
 --gpu_id 1\
 --init_lr 0.001\
 --max_epoch 5\
  --train_batch_size 4\
 --val_batch_size 8\
 --dataset_names '/media3/Timeseries-PILE/forecasting/autoformer/electricity.csv'\
 --level 14
 python3 scripts/finetuning/imputation.py\
 --finetuning_mode 'linear-probing'\
 --config 'configs/imputation/linear_probing.yaml'\
 --gpu_id 1\
 --init_lr 0.001\
 --max_epoch 5\
  --train_batch_size 4\
 --val_batch_size 8\
 --dataset_names '/media3/Timeseries-PILE/forecasting/autoformer/electricity.csv'\
 --level 15
 python3 scripts/finetuning/imputation.py\
 --finetuning_mode 'linear-probing'\
 --config 'configs/imputation/linear_probing.yaml'\
 --gpu_id 1\
 --init_lr 0.001\
 --max_epoch 5\
  --train_batch_size 4\
 --val_batch_size 8\
 --dataset_names '/media3/Timeseries-PILE/forecasting/autoformer/electricity.csv'\
 --level 16
 python3 scripts/finetuning/imputation.py\
 --finetuning_mode 'linear-probing'\
 --config 'configs/imputation/linear_probing.yaml'\
 --gpu_id 1\
 --init_lr 0.001\
 --max_epoch 5\
  --train_batch_size 4\
 --val_batch_size 8\
 --dataset_names '/media3/Timeseries-PILE/forecasting/autoformer/electricity.csv'\
 --level 17
 python3 scripts/finetuning/imputation.py\
 --finetuning_mode 'linear-probing'\
 --config 'configs/imputation/linear_probing.yaml'\
 --gpu_id 1\
 --init_lr 0.001\
 --max_epoch 5\
  --train_batch_size 4\
 --val_batch_size 8\
 --dataset_names '/media3/Timeseries-PILE/forecasting/autoformer/electricity.csv'\
 --level 18
 python3 scripts/finetuning/imputation.py\
 --finetuning_mode 'linear-probing'\
 --config 'configs/imputation/linear_probing.yaml'\
 --gpu_id 1\
 --init_lr 0.001\
 --max_epoch 5\
  --train_batch_size 4\
 --val_batch_size 8\
 --dataset_names '/media3/Timeseries-PILE/forecasting/autoformer/electricity.csv'\
 --level 19
 python3 scripts/finetuning/imputation.py\
 --finetuning_mode 'linear-probing'\
 --config 'configs/imputation/linear_probing.yaml'\
 --gpu_id 1\
 --init_lr 0.001\
 --max_epoch 5\
  --train_batch_size 4\
 --val_batch_size 8\
 --dataset_names '/media3/Timeseries-PILE/forecasting/autoformer/electricity.csv'\
 --level 20
 python3 scripts/finetuning/imputation.py\
 --finetuning_mode 'linear-probing'\
 --config 'configs/imputation/linear_probing.yaml'\
 --gpu_id 1\
 --init_lr 0.001\
 --max_epoch 5\
  --train_batch_size 4\
 --val_batch_size 8\
 --dataset_names '/media3/Timeseries-PILE/forecasting/autoformer/electricity.csv'\
 --level 21
 python3 scripts/finetuning/imputation.py\
 --finetuning_mode 'linear-probing'\
 --config 'configs/imputation/linear_probing.yaml'\
 --gpu_id 1\
 --init_lr 0.001\
 --max_epoch 5\
  --train_batch_size 4\
 --val_batch_size 8\
 --dataset_names '/media3/Timeseries-PILE/forecasting/autoformer/electricity.csv'\
 --level 22
 python3 scripts/finetuning/imputation.py\
 --finetuning_mode 'linear-probing'\
 --config 'configs/imputation/linear_probing.yaml'\
 --gpu_id 1\
 --init_lr 0.001\
 --max_epoch 5\
  --train_batch_size 4\
 --val_batch_size 8\
 --dataset_names '/media3/Timeseries-PILE/forecasting/autoformer/electricity.csv'\
 --level 23
